const filmes = [
    {
        id: 1,
        title: "O Poderoso Chefão",
        description: "A saga da família mafiosa Corleone, abordando temas de poder e lealdade.",
        image: "filmes/1.jpg",
        genero: ["Crime", "Drama"],
        idade: "18",
        ano: "1972",
    },
    {
        id: 2,
        title: "O Mágico de Oz",
        description: "A aventura de Dorothy em um mundo mágico, buscando voltar para casa.",
        image: "filmes/2.jpg",
        genero: ["Fantasia", "Aventura"],
        idade: "L",
        ano: "1939",
    },
    {
        id: 3,
        title: "Cidadão Kane",
        description: "A vida do magnata da imprensa Charles Foster Kane, explorando sua busca por felicidade.",
        image: "filmes/3.jpg",
        genero: ["Drama", "Mistério"],
        idade: "L",
        ano: "1941",
    },
    {
        id: 4,
        title: "Um Sonho de Liberdade",
        description: "A história de Andy Dufresne, um homem injustamente preso que busca liberdade.",
        image: "filmes/4.jpg",
        genero: ["Drama", "Crime"],
        idade: "L",
        ano: "1994",
    },
    {
        id: 5,
        title: "Pulp Fiction - Tempo de Violência",
        description: "Várias histórias interligadas sobre crime e redenção em Los Angeles.",
        image: "filmes/5.jpg",
        genero: ["Crime", "Drama"],
        idade: "18",
        ano: "1994",
    },
    {
        id: 6,
        title: "Casablanca",
        description: "Uma história de amor ambientada na Segunda Guerra Mundial em Casablanca.",
        image: "filmes/6.jpg",
        genero: ["Drama", "Romance"],
        idade: "L",
        ano: "1942",
    },
    {
        id: 7,
        title: "O Poderoso Chefão: Parte II",
        description: "A sequência que continua a saga da família Corleone em duas linhas do tempo.",
        image: "filmes/7.jpg",
        genero: ["Crime", "Drama"],
        idade: "18",
        ano: "1974",
    },
    {
        id: 8,
        title: "E.T. - O Extraterrestre",
        description: "A amizade entre um garoto e um alienígena perdido que deseja voltar para casa.",
        image: "filmes/8.jpg",
        genero: ["Fantasia", "Aventura"],
        idade: "L",
        ano: "1982",
    },
    {
        id: 9,
        title: "2001: Uma Odisséia no Espaço",
        description: "Uma jornada épica que explora a evolução humana e o espaço.",
        image: "filmes/9.jpg",
        genero: ["Ficção Científica", "Aventura"],
        idade: "L",
        ano: "1968",
    },
    {
        id: 10,
        title: "A Lista de Schindler",
        description: "A história de Oskar Schindler e sua tentativa de salvar judeus durante o Holocausto.",
        image: "filmes/10.jpg",
        genero: ["Drama", "Guerra"],
        idade: "14",
        ano: "1993",
    },
    {
        id: 11,
        title: "Star Wars: Uma Nova Esperança",
        description: "A luta da Aliança Rebelde contra o Império e o surgimento de Luke Skywalker.",
        image: "filmes/11.jpg",
        genero: ["Ficção Científica", "Aventura"],
        idade: "L",
        ano: "1977",
    },
    {
        id: 12,
        title: "De Volta Para o Futuro",
        description: "As aventuras de Marty McFly, que viaja no tempo para salvar seu futuro.",
        image: "filmes/12.jpg",
        genero: ["Ficção Científica", "Aventura"],
        idade: "L",
        ano: "1985",
    },
    {
        id: 13,
        title: "Indiana Jones e os Caçadores da Arca Perdida",
        description: "As aventuras do arqueólogo Indiana Jones em busca da Arca da Aliança.",
        image: "filmes/13.jpg",
        genero: ["Aventura", "Ação"],
        idade: "L",
        ano: "1981",
    },
    {
        id: 14,
        title: "Forrest Gump: O Contador de Histórias",
        description: "A vida extraordinária de Forrest Gump, que testemunha eventos históricos.",
        image: "filmes/14.jpg",
        genero: ["Drama", "Romance"],
        idade: "L",
        ano: "1994",
    },
    {
        id: 15,
        title: "...E o Vento Levou",
        description: "A história de Scarlett O'Hara e sua luta pela sobrevivência durante a Guerra Civil.",
        image: "filmes/15.jpg",
        genero: ["Drama", "Romance"],
        idade: "L",
        ano: "1939",
    },
    {
        id: 16,
        title: "O Sol é Para Todos",
        description: "Um advogado defende um homem negro acusado injustamente de estuprar uma mulher branca.",
        image: "filmes/16.jpg",
        genero: ["Drama"],
        idade: "12",
        ano: "1962",
    },
    {
        id: 17,
        title: "Apocalypse Now",
        description: "Uma jornada surreal na Guerra do Vietnã, com uma missão para eliminar um coronel.",
        image: "filmes/17.jpg",
        genero: ["Guerra", "Drama"],
        idade: "18",
        ano: "1979",
    },
    {
        id: 18,
        title: "Noivo Neurótico, Noiva Nervosa",
        description: "A história de um casal em conflito enquanto lidam com suas neuroses.",
        image: "filmes/18.jpg",
        genero: ["Comédia", "Romance"],
        idade: "12",
        ano: "1977",
    },
    {
        id: 19,
        title: "Os Bons Companheiros",
        description: "A vida de um jovem que se torna um gângster e sua descida ao crime.",
        image: "filmes/19.jpg",
        genero: ["Crime", "Drama"],
        idade: "18",
        ano: "1990",
    },
    {
        id: 20,
        title: "A Felicidade Não se Compra",
        description: "Um homem aprende o valor da vida e da amizade em um Natal mágico.",
        image: "filmes/20.jpg",
        genero: ["Drama", "Fantasia"],
        idade: "L",
        ano: "1946",
    },
    {
        id: 21,
        title: "Chinatown",
        description: "Um detetive investiga um caso de corrupção e um mistério envolvendo água em Los Angeles.",
        image: "filmes/21.jpg",
        genero: ["Mistério", "Drama"],
        idade: "14",
        ano: "1974",
    },
    {
        id: 22,
        title: "O Silêncio dos Inocentes",
        description: "Uma jovem agente do FBI busca a ajuda de um assassino para capturar outro criminoso.",
        image: "filmes/22.jpg",
        genero: ["Suspense", "Crime"],
        idade: "18",
        ano: "1991",
    },
    {
        id: 23,
        title: "Lawrence da Arábia",
        description: "A vida do oficial britânico T.E. Lawrence e sua luta na Primeira Guerra Mundial.",
        image: "filmes/23.jpg",
        genero: ["Aventura", "Biografia"],
        idade: "12",
        ano: "1962",
    },
    {
        id: 24,
        title: "Tubarão",
        description: "Um grande tubarão ataca uma pequena cidade, enquanto um policial tenta detê-lo.",
        image: "filmes/24.jpg",
        genero: ["Terror", "Aventura"],
        idade: "14",
        ano: "1975",
    },
    {
        id: 25,
        title: "A Noviça Rebelde",
        description: "Uma governanta se torna parte da vida de uma família austríaca antes da guerra.",
        image: "filmes/25.jpg",
        genero: ["Musical", "Drama"],
        idade: "L",
        ano: "1965",
    },
    {
        id: 26,
        title: "Cantando na Chuva",
        description: "Uma comédia musical sobre a transição do cinema mudo para o sonoro.",
        image: "filmes/26.jpg",
        genero: ["Musical", "Comédia"],
        idade: "L",
        ano: "1952",
    },
    {
        id: 27,
        title: "Clube dos Cinco",
        description: "Cinco estudantes se encontram em detenção e descobrem mais sobre si mesmos.",
        image: "filmes/27.jpg",
        genero: ["Comédia", "Drama"],
        idade: "12",
        ano: "1985",
    },
    {
        id: 28,
        title: "A Primeira Noite de um Homem",
        description: "Um jovem se envolve com uma mulher mais velha enquanto se adapta à vida adulta.",
        image: "filmes/28.jpg",
        genero: ["Drama", "Romance"],
        idade: "14",
        ano: "1967",
    },
    {
        id: 29,
        title: "Blade Runner, o Caçador de Andróides",
        description: "Um caçador de andróides busca eliminar robôs fugitivos em uma Los Angeles futurista.",
        image: "filmes/29.jpg",
        genero: ["Ficção Científica", "Thriller"],
        idade: "16",
        ano: "1982",
    },
    {
        id: 30,
        title: "Um Estranho no Ninho",
        description: "Um homem é internado em um sanatório e desafia a autoridade dos cuidadores.",
        image: "filmes/30.jpg",
        genero: ["Drama"],
        idade: "14",
        ano: "1975",
    },
    {
        id: 31,
        title: "A Princesa Prometida",
        description: "Uma épica história de amor, aventura e resgate em um mundo de fantasia.",
        image: "filmes/31.jpg",
        genero: ["Fantasia", "Aventura"],
        idade: "L",
        ano: "1987",
    },
    {
        id: 32,
        title: "Star Wars: O Império Contra-Ataca",
        description: "Os rebeldes lutam contra o Império, enquanto Luke Skywalker busca o treinamento de Yoda.",
        image: "filmes/32.jpg",
        genero: ["Ficção Científica", "Aventura"],
        idade: "L",
        ano: "1980",
    },
    {
        id: 33,
        title: "Fargo",
        description: "Uma história de crime e humor, envolvendo um sequestro que dá errado.",
        image: "filmes/33.jpg",
        genero: ["Crime", "Drama"],
        idade: "16",
        ano: "1996",
    },
    {
        id: 34,
        title: "Beleza Americana",
        description: "A crise da meia-idade de um homem que se vê obcecado pela melhor amiga de sua filha.",
        image: "filmes/34.jpg",
        genero: ["Drama", "Comédia"],
        idade: "16",
        ano: "1999",
    },
    {
        id: 35,
        title: "Laranja Mecânica",
        description: "A história de um jovem delinquente e seu envolvimento em um experimento de reabilitação.",
        image: "filmes/35.jpg",
        genero: ["Ficção Científica", "Crime"],
        idade: "18",
        ano: "1971",
    },
    {
        id: 36,
        title: "Curtindo a Vida Adoidado",
        description: "Um jovem faz uma pausa na escola para um dia de aventuras em Chicago.",
        image: "filmes/36.jpg",
        genero: ["Comédia"],
        idade: "L",
        ano: "1986",
    },
    {
        id: 37,
        title: "Dr. Fantástico",
        description: "Uma sátira sobre a Guerra Fria e um general que deseja destruir o mundo.",
        image: "filmes/37.jpg",
        genero: ["Comédia", "Guerra"],
        idade: "14",
        ano: "1964",
    },
    {
        id: 38,
        title: "Harry e Sally - Feitos Um para o Outro",
        description: "A relação entre Harry e Sally, explorando se homens e mulheres podem ser amigos.",
        image: "filmes/38.jpg",
        genero: ["Comédia", "Romance"],
        idade: "12",
        ano: "1989",
    },
    {
        id: 39,
        title: "O Iluminado",
        description: "Um escritor e sua família ficam presos em um hotel assombrado.",
        image: "filmes/39.jpg",
        genero: ["Terror", "Suspense"],
        idade: "16",
        ano: "1980",
    },
    {
        id: 40,
        title: "Clube da Luta",
        description: "Um homem insatisfeito encontra um novo propósito em um clube de luta clandestino.",
        image: "filmes/40.jpg",
        genero: ["Drama", "Suspense"],
        idade: "18",
        ano: "1999",
    },
    {
        id: 41,
        title: "Psicose",
        description: "Um thriller psicológico que segue um assassino em um motel isolado.",
        image: "filmes/41.jpg",
        genero: ["Terror", "Suspense"],
        idade: "14",
        ano: "1960",
    },
    {
        id: 42,
        title: "Alien, o Oitavo Passageiro",
        description: "Uma tripulação de nave espacial enfrenta uma criatura alienígena mortal.",
        image: "filmes/42.jpg",
        genero: ["Ficção Científica", "Terror"],
        idade: "16",
        ano: "1979",
    },
    {
        id: 43,
        title: "Toy Story",
        description: "A vida secreta dos brinquedos quando seus donos não estão por perto.",
        image: "filmes/43.jpg",
        genero: ["Animação", "Aventura"],
        idade: "L",
        ano: "1995",
    },
    {
        id: 44,
        title: "Matrix",
        description: "Um programador descobre a verdade sobre a realidade e sua luta contra as máquinas.",
        image: "filmes/44.jpg",
        genero: ["Ficção Científica", "Ação"],
        idade: "16",
        ano: "1999",
    },
    {
        id: 45,
        title: "Titanic",
        description: "Uma história de amor entre Jack e Rose a bordo do infame navio Titanic.",
        image: "filmes/45.jpg",
        genero: ["Drama", "Romance"],
        idade: "12",
        ano: "1997",
    },
    {
        id: 46,
        title: "O Resgate do Soldado Ryan",
        description: "Uma missão para resgatar um soldado durante a Segunda Guerra Mundial.",
        image: "filmes/46.jpg",
        genero: ["Guerra", "Drama"],
        idade: "16",
        ano: "1998",
    },
    {
        id: 47,
        title: "Quanto Mais Quente Melhor",
        description: "Dois músicos se disfarçam de mulheres para escapar de gângsteres.",
        image: "filmes/47.jpg",
        genero: ["Comédia", "Romance"],
        idade: "12",
        ano: "1959",
    },
    {
        id: 48,
        title: "Os Suspeitos",
        description: "Um detetive investiga um caso complicado envolvendo um crime misterioso.",
        image: "filmes/48.jpg",
        genero: ["Crime", "Suspense"],
        idade: "16",
        ano: "1995",
    },
    {
        id: 49,
        title: "Janela Indiscreta",
        description: "Um fotógrafo convalescente suspeita que um crime ocorreu em seu bairro.",
        image: "filmes/49.jpg",
        genero: ["Mistério", "Suspense"],
        idade: "12",
        ano: "1954",
    },
    {
        id: 50,
        title: "Jurassic Park: O Parque dos Dinossauros",
        description: "Um parque temático de dinossauros sai do controle quando os animais escapam.",
        image: "filmes/50.jpg",
        genero: ["Aventura", "Ficção Científica"],
        idade: "12",
        ano: "1993",
    },
    {
        id: 51,
        title: "O Grande Lebowski",
        description: "Um 'cara' é puxado para um mundo de crime por causa de um erro de identidade.",
        image: "filmes/51.jpg",
        genero: ["Comédia", "Crime"],
        idade: "16",
        ano: "1998",
    },
    {
        id: 52,
        title: "A Malvada",
        description: "Uma atriz ambiciosa que faz de tudo para alcançar a fama.",
        image: "filmes/52.jpg",
        genero: ["Drama"],
        idade: "12",
        ano: "1950",
    },
    {
        id: 53,
        title: "Gênio Indomável",
        description: "Um jovem prodígio em matemática enfrenta seus traumas e encontra um mentor.",
        image: "filmes/53.jpg",
        genero: ["Drama"],
        idade: "12",
        ano: "1997",
    },
    {
        id: 54,
        title: "Butch Cassidy",
        description: "A história real de dois bandidos que se tornam lendas do Velho Oeste.",
        image: "filmes/54.jpg",
        genero: ["Aventura", "Drama"],
        idade: "12",
        ano: "1969",
    },
    {
        id: 55,
        title: "Taxi Driver - Motorista de Táxi",
        description: "A história de um veterano do Vietnã que se torna um taxista em Nova York.",
        image: "filmes/55.jpg",
        genero: ["Drama", "Crime"],
        idade: "18",
        ano: "1976",
    },
    {
        id: 56,
        title: "Brilho Eterno de uma Mente sem Lembranças",
        description: "Um homem busca apagar memórias de um amor fracassado.",
        image: "filmes/56.jpg",
        genero: ["Romance", "Ficção Científica"],
        idade: "14",
        ano: "2004",
    },
    {
        id: 57,
        title: "Batman: O Cavaleiro das Trevas",
        description: "Batman enfrenta o Coringa enquanto a cidade de Gotham desmorona.",
        image: "filmes/57.jpg",
        genero: ["Ação", "Crime"],
        idade: "14",
        ano: "2008",
    },
    {
        id: 58,
        title: "Crepúsculo dos Deuses",
        description: "A história de uma estrela de cinema em decadência e seu relacionamento com um roteirista.",
        image: "filmes/58.jpg",
        genero: ["Drama", "Mistério"],
        idade: "16",
        ano: "1950",
    },
    {
        id: 59,
        title: "Thelma & Louise",
        description: "Duas mulheres embarcam em uma viagem que se transforma em fuga.",
        image: "filmes/59.jpg",
        genero: ["Drama", "Aventura"],
        idade: "14",
        ano: "1991",
    },
    {
        id: 60,
        title: "O Fabuloso Destino de Amélie Poulain",
        description: "Uma jovem mulher decide mudar a vida das pessoas ao seu redor para melhor.",
        image: "filmes/60.jpg",
        genero: ["Comédia", "Romance"],
        idade: "L",
        ano: "2001",
    },
    {
        id: 61,
        title: "Amor, Sublime Amor",
        description: "Um romance moderno entre duas famílias rivais em Nova York.",
        image: "filmes/61.jpg",
        genero: ["Musical", "Drama"],
        idade: "12",
        ano: "1961",
    },
    {
        id: 62,
        title: "Intriga Internacional",
        description: "Um homem é confundido com um espião e se vê em uma corrida contra o tempo.",
        image: "filmes/62.jpg",
        genero: ["Ação", "Aventura"],
        idade: "12",
        ano: "1959",
    },
    {
        id: 63,
        title: "Feitiço do Tempo",
        description: "Um repórter se vê preso em um loop temporal, revivendo o mesmo dia.",
        image: "filmes/63.jpg",
        genero: ["Comédia", "Fantasia"],
        idade: "L",
        ano: "1993",
    },
    {
        id: 64,
        title: "Mary Poppins",
        description: "Uma babá mágica transforma a vida de duas crianças e sua família.",
        image: "filmes/64.jpg",
        genero: ["Fantasia", "Musical"],
        idade: "L",
        ano: "1964",
    },
    {
        id: 65,
        title: "Touro Indomável",
        description: "A vida do boxeador Jake LaMotta, mostrando suas vitórias e quedas.",
        image: "filmes/65.jpg",
        genero: ["Biografia", "Drama"],
        idade: "16",
        ano: "1980",
    },
    {
        id: 66,
        title: "O Rei Leão",
        description: "A jornada de Simba, um jovem leão, em busca de seu lugar no ciclo da vida.",
        image: "filmes/66.jpg",
        genero: ["Animação", "Aventura"],
        idade: "L",
        ano: "1994",
    },
    {
        id: 67,
        title: "Avatar",
        description: "Um ex-fuzileiro se infiltra em uma raça alienígena em um mundo chamado Pandora.",
        image: "filmes/67.jpg",
        genero: ["Ficção Científica", "Aventura"],
        idade: "12",
        ano: "2009",
    },
    {
        id: 68,
        title: "Monty Python Em Busca do Cálice Sagrado",
        description: "Uma comédia satírica sobre a busca do Santo Graal por cavaleiros medievais.",
        image: "filmes/68.jpg",
        genero: ["Comédia", "Aventura"],
        idade: "L",
        ano: "1975",
    },
    {
        id: 69,
        title: "Gladiador",
        description: "Um general romano é traído e se torna um gladiador em busca de vingança.",
        image: "filmes/69.jpg",
        genero: ["Ação", "Drama"],
        idade: "16",
        ano: "2000",
    },
    {
        id: 70,
        title: "Um Corpo que Cai",
        description: "Um detetive se torna obcecado por uma mulher após um caso de assassinato.",
        image: "filmes/70.jpg",
        genero: ["Mistério", "Romance"],
        idade: "16",
        ano: "1958",
    },
    {
        id: 71,
        title: "Quase Famosos",
        description: "Um jovem jornalista acompanha uma banda de rock em sua turnê nos anos 70.",
        image: "filmes/71.jpg",
        genero: ["Drama", "Música"],
        idade: "14",
        ano: "2000",
    },
    {
        id: 72,
        title: "O Jovem Frankenstein",
        description: "Uma comédia que parodia os clássicos filmes de terror de Frankenstein.",
        image: "filmes/72.jpg",
        genero: ["Comédia", "Terror"],
        idade: "12",
        ano: "1974",
    },
    {
        id: 73,
        title: "Todos os Homens do Presidente",
        description: "A investigação jornalística que expôs o escândalo Watergate nos anos 70.",
        image: "filmes/73.jpg",
        genero: ["Drama", "História"],
        idade: "14",
        ano: "1976",
    },
    {
        id: 74,
        title: "Banzé no Oeste",
        description: "Uma comédia sobre um cowboy que luta contra um bandido em um vilarejo.",
        image: "filmes/74.jpg",
        genero: ["Comédia", "Faroeste"],
        idade: "12",
        ano: "1974",
    },
    {
        id: 75,
        title: "A Ponte do Rio Kwai",
        description: "Prisioneiros de guerra britânicos constroem uma ponte para os japoneses durante a Segunda Guerra Mundial.",
        image: "filmes/75.jpg",
        genero: ["Guerra", "Drama"],
        idade: "14",
        ano: "1957",
    },
    {
        id: 76,
        title: "O Segredo de Brokeback Mountain",
        description: "O amor proibido entre dois vaqueiros no oeste americano.",
        image: "filmes/76.jpg",
        genero: ["Drama", "Romance"],
        idade: "16",
        ano: "2005",
    },
    {
        id: 77,
        title: "Os Caça-Fantasmas",
        description: "Um grupo de cientistas combate fantasmas e entidades sobrenaturais em Nova York.",
        image: "filmes/77.jpg",
        genero: ["Comédia", "Fantasia"],
        idade: "L",
        ano: "1984",
    },
    {
        id: 78,
        title: "12 Homens e uma Sentença",
        description: "Um júri discute o destino de um réu acusado de homicídio.",
        image: "filmes/78.jpg",
        genero: ["Drama"],
        idade: "12",
        ano: "1957",
    },
    {
        id: 79,
        title: "Wall-E",
        description: "Um robô solitário busca vida em um planeta Terra abandonado.",
        image: "filmes/79.jpg",
        genero: ["Animação", "Aventura"],
        idade: "L",
        ano: "2008",
    },
    {
        id: 80,
        title: "Amadeus",
        description: "A vida de Mozart e a rivalidade com o compositor Salieri.",
        image: "filmes/80.jpg",
        genero: ["Biografia", "Drama"],
        idade: "14",
        ano: "1984",
    },
    {
        id: 81,
        title: "Senhor dos Anéis: A Sociedade do Anel",
        description: "Um hobbit parte em uma jornada para destruir um poderoso anel.",
        image: "filmes/81.jpg",
        genero: ["Fantasia", "Aventura"],
        idade: "12",
        ano: "2001",
    },
    {
        id: 82,
        title: "Senhor dos Anéis: O Retorno do Rei",
        description: "A batalha final pela Terra-média e o destino do Um Anel.",
        image: "filmes/82.jpg",
        genero: ["Fantasia", "Aventura"],
        idade: "12",
        ano: "2003",
    },
    {
        id: 83,
        title: "O Silêncio dos Inocentes",
        description: "Uma jovem agente do FBI busca a ajuda de um assassino em série para capturar outro criminoso.",
        image: "filmes/83.jpg",
        genero: ["Terror", "Suspense"],
        idade: "18",
        ano: "1991",
    },
    {
        id: 84,
        title: "Os Intocáveis",
        description: "Um agente da lei combate o crime organizado na Chicago dos anos 30.",
        image: "filmes/84.jpg",
        genero: ["Crime", "Drama"],
        idade: "16",
        ano: "1987",
    },
    {
        id: 85,
        title: "O Mágico de Oz",
        description: "Uma menina é levada para um mundo mágico onde vive aventuras incríveis.",
        image: "filmes/85.jpg",
        genero: ["Fantasia", "Musical"],
        idade: "L",
        ano: "1939",
    },
    {
        id: 86,
        title: "O Show de Truman",
        description: "Um homem descobre que sua vida é um reality show.",
        image: "filmes/86.jpg",
        genero: ["Comédia", "Drama"],
        idade: "12",
        ano: "1998",
    },
    {
        id: 87,
        title: "A Vida é Bela",
        description: "Um pai usa a imaginação para proteger seu filho em meio a uma guerra.",
        image: "filmes/87.jpg",
        genero: ["Drama", "Guerra"],
        idade: "10",
        ano: "1997",
    },
    {
        id: 88,
        title: "Os Infiltrados",
        description: "Um policial se infiltra na máfia enquanto um mafioso se infiltra na polícia.",
        image: "filmes/88.jpg",
        genero: ["Crime", "Suspense"],
        idade: "16",
        ano: "2006",
     },
     {
        id: 89,
        title: "A Rede Social",
        description: "A criação do Facebook e os conflitos pessoais de Mark Zuckerberg.",
        image: "filmes/89.jpg",
        genero: ["Drama", "Biografia"],
        idade: "12",
        ano: "2010",
     },
     {
        id: 90,
        title: "Cisne Negro",
        description: "Uma bailarina enfrenta sua própria sanidade enquanto se prepara para um grande papel.",
        image: "filmes/90.jpg",
        genero: ["Drama", "Suspense"],
        idade: "16",
        ano: "2010",
     },
     {
        id: 91,
        title: "O Curioso Caso de Benjamin Button",
        description: "Um homem nasce velho e envelhece para o que parece ser uma criança.",
        image: "filmes/91.jpg",
        genero: ["Drama", "Fantasia"],
        idade: "12",
        ano: "2008",
     },
     {
        id: 92,
        title: "Intocáveis",
        description: "A amizade entre um tetraplégico e seu cuidador inesperado.",
        image: "filmes/92.jpg",
        genero: ["Drama", "Comédia"],
        idade: "12",
        ano: "2011",
     },
     {
        id: 93,
        title: "O Lobo de Wall Street",
        description: "A vida extravagante de um corretor de ações em Nova York.",
        image: "filmes/93.jpg",
        genero: ["Comédia", "Drama"],
        idade: "18",
        ano: "2013",
     },
     {
        id: 94,
        title: "Birdman",
        description: "Um ator em decadência tenta reviver sua carreira na Broadway.",
        image: "filmes/94.jpg",
        genero: ["Comédia", "Drama"],
        idade: "16",
        ano: "2014",
     },
     {
        id: 95,
        title: "A Chegada",
        description: "Uma linguista é recrutada para decifrar uma linguagem alienígena.",
        image: "filmes/95.jpg",
        genero: ["Ficção Científica", "Drama"],
        idade: "12",
        ano: "2016",
     },
     {
        id: 96,
        title: "La La Land: Cantando Estações",
        description: "Um romance musical entre um músico e uma aspirante a atriz em Los Angeles.",
        image: "filmes/96.jpg",
        genero: ["Musical", "Romance"],
        idade: "12",
        ano: "2016",
     },
     {
        id: 97,
        title: "Dunkirk",
        description: "A evacuação de soldados britânicos na Segunda Guerra Mundial.",
        image: "filmes/97.jpg",
        genero: ["Guerra", "Drama"],
        idade: "12",
        ano: "2017",
     },
     {
        id: 98,
        title: "O Farol",
        description: "Dois faroleiros isolados enfrentam a loucura em uma ilha remota.",
        image: "filmes/98.jpg",
        genero:["Terror", "Drama"],
        idade: "16",
        ano: "2019",
     },
     {
        id: 99,
        title: "Parasita",
        description: "Uma família pobre se infiltra na vida de uma família rica.",
        image: "filmes/99.jpg",
        genero: ["Drama", "Suspense"],
        idade: "16",
        ano: "2019",
     },
     {
        id: 100,
        title: "1917",
        description: "Dois soldados britânicos têm uma missão para entregar uma mensagem vital na Primeira Guerra Mundial.",
        image: "filmes/100.jpg",
        genero: ["Guerra", "Drama"],
        idade: "14",
        ano: "2019",
     }
];

